name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build Playwright Docker image
        run: npm run docker:build
      - name: Run Playwright tests in Docker
        run: npm run docker:run 'npm run pretest && npm run build:html && npx playwright test'
      - uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
